### ISSUE TITLE
Squid3 runs out of  file descriptors

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/squid3-windows#31]
Hi
I have sometimes trouble with your build with Squid3 (with cache enabled)
I says it runs out of file descriptors
Because of that, it sometimes doesn't load whole images (partly downloaded)
can you compile it with more file descriptors?
I think you can compile it with the option "--with-maxfd=[and some numbers]" try with number 65536
It can also decrease it for max supported (in cygwin)
I hope the build you next release will be better

**Comment by ea-at-diladele-com** [comment]
If you run "squid -v" you will see that the number of descriptors is already high enough (65 thousand).
The problem is that Windows c runtime has a limit of 512 only. We will check what can be done in the next release.

Could you please specify the windows version you are using and how by how many clients you start experience this problems?

Thank you very much!

**Comment by j19861986** [comment]
I used Windows 8.1
and I only used it for one client, when trying to load many tabs, the problem comes
I have checked squid log, it has only 256 available descriptors
It would help if had 512, double the 256.

**Comment by j19861986** [comment]
I mean it would really help if could have really high File Descriptors

**Comment by ea-at-diladele-com** [comment]
In the next release we will increase it to at least 2048. Thank you very much for reporting this issue!

**Comment by ra-at-diladele-com** [comment]
Build updated on the site - please check if the FD number is higher now.

**Comment by ra-at-diladele-com** [comment]
Bug is closed.
